services:
  db:
    image: mysql:5.7
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=dlp_db
      - MYSQL_USER=dlp_user
      - MYSQL_PASSWORD=dlp_password
      - MYSQL_ROOT_PASSWORD=root_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  queue:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=us-east-1
      - HOSTNAME=queue
      - HOSTNAME_EXTERNAL=queue
      - LOCALSTACK_API_KEY=
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=us-east-1

  backend:
    build:
      context: ./backend
    command: sh -c "python wait_for_queue.py && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=dlp_db
      - DB_USER=dlp_user
      - DB_PASS=dlp_password
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=us-east-1
      - SQS_QUEUE_URL=http://queue:4566/000000000000/dlp-queue
      - SQS_ENDPOINT_URL=http://queue:4566
      - SQS_QUEUE_NAME=dlp-queue
      - SLACK_BOT_TOKEN=xoxb-9238967559762-9227239254263-vJlpTZcILakvLubnOozYxee4
    depends_on:
      - db
      - queue

  dlp_worker:
    build:
      context: ./dlp_worker
    command: sh -c 'while true; do echo "Worker container is running..."; python worker.py; sleep 5; done'
    volumes:
      - ./dlp_worker:/app
    environment:
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=us-east-1
      - SQS_QUEUE_URL=http://queue:4566/000000000000/dlp-queue
      - DJANGO_API_URL=http://backend:8000/api
      - SQS_ENDPOINT_URL=http://queue:4566
      - SQS_QUEUE_NAME=dlp-queue
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
    depends_on:
      - queue
      - backend

volumes:
  db_data:
