# Generated by Django 4.2.7 on 2025-07-23 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('regex', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DetectedLeak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_content', models.TextField()),
                ('channel', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dlp_api.pattern')),
            ],
        ),
    ]
